dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-02/run.sh | bash
notifications:
  slack:
    secure: gmN3pOa+D7Rvy1dI90rs3qGEFOMxueciYpDJn7X8nZ0En6dOpHLWq1yIJRm0Yl/wonPmnsaVE1Yjo4cVxUTUjwA3o7s70CfGNbDH/0aicLlwZXKOOJR8Q0695aIz38Ju1KbibtHUF07UVVKMEYIAF2B9ClghJ7j7i29lBWVbuY96IMZUW9FWbPkS2ID111Ww2z8Fnd/KZDuWDEBxxX5/9VjToYrUuBxK2gXoe5EHO536NQQC/liA9t1SJ1rRIW8Lm5W4iirq8HljNqcHexRfVyv/baz9JZm0PIA+ayDyRveSc8DmFh1IUw27VnjBMYZEQsM+Ia6Hs99LDrlSzIYUD9k2IO3z3Ub8/LW52AKTkjfBMbM0Hlw5sflztAJEm/gWp0ntnRCE9LZ/I55G9gLHVJIg8M55N3AmNkzeUNc1c3uqnUxFQcJ8ahYjtOAIFWooXrTtHnnPOuoS+CI+pAY4JZrzIK1G13epoEpKd/4CsKnKNs7EBX0RQhdY5+xJyM9Mi3NFBj3KYsKFIxhUgikKZRuUid0H2DqD7m/Lp7rbWNtyaj6RY5JAywPTeudybeWBcgCKQKChyEllf26SnjOCmDCjlbwmQE8CIV8B5wBulgwQ2EbheysZ+uuscGlvcv1czymgBe5dPMBoDAZLQXmvUgzsReaeoTHo2gNyz6UKhHc=
